[project]
name = "cv_demo"
version = "0.1.0"
description = "A computer vision pytorch demo project."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.6.3",
    "torch>=2.4.0",
    "torchvision>=0.19.0",
]
